### PR TITLE
Fixed typo in build output

### PR DESCRIPTION
**Pull request by PeterMitrano**
variables was mispelled

### CODE REVIEW

**Comment by scottdarch** [comment]
Thanks!

**Comment by PeterMitrano** [comment]
I really really love this tool. Looking forward to making meaningful contributions soon

**Comment by scottdarch** [comment]
Remember that the mainline is at EOL. I've been doing a complete rewrite you could contribute to. The work is coming together for that version under the develop branch. Progress has been slow because I have not had any other contributors.

**Comment by PeterMitrano** [comment]
Oh ok, didn't know that. I'll check out the develop branch instead.

**Comment by scottdarch** [comment]
Develop doesn't work yet really :smile: It's a work in progress. But if you do want to build a really cool tool it's the place to start.

**Comment by PeterMitrano** [comment]
Yep yep! I also have decent experience migrating linux tools to windows, so
I might take a crack at compiling Arturo with msvc...

**Pull request merged**
