### PR TITLE
Fix for #29, making libraries optional

### PR DESCRIPTION
**Pull request by scottdarch**
If you don't need 'em you don't need 'em.
Thanks to @Mausy5043 for diagnosing this issue.

### CODE REVIEW

**Comment by scottdarch** [comment]
I've merged #30 BTW. So you'll want to just sync master when you try again. I'll leave this bug open until @hachpai confirms the fix.

**Comment by hachpai** [comment]
It was cleaned. :-)

**Comment by Mausy5043** [comment]
Please post the output.

**Comment by hachpai** [comment]
Output? It's not what i've posted?

**Comment by Mausy5043** [comment]
It says `FAILED` for the core libs and the user libs. 
Look at my output to compare (http://pastebin.com/pcgbtuLC). However, the compile completes succesfully for me.
Could you post a bit more of the output. (tip: use pastebin).

**Comment by hachpai** [comment]
I don't have more output, it exits directly after the failed of arduino core library.

**Comment by Mausy5043** [comment]
I'm using arduino IDE 1.0.1 w/ Arturo on a Raspberry Pi. I see you're problem seems to be with OSX (what version are you on?)
I have IDE 1.0.5 w/ OSX 10.10.3. I'll see if I can test that sometime tomorrow. 

The error you're getting though really suggests the core libraries are not optional.
Try this:
- delete the `Arturo` directory.
- `git clone https://github.com/scottdarch/Arturo.git`
- `make; make install`
  Then `ano clean` and `ano build` the arduino project.

**Comment by hachpai** [comment]
Same configuration 10.10.3 and IDE 1.0.5. I've already remove/reinstall everything

**Comment by scottdarch** [comment]
@hachpai , do you have a repo I can clone to try and reproduce locally?

**Comment by Mausy5043** [comment]
when did you reinstall Arturo?

**Comment by hachpai** [comment]
I just do a `ano init`  and a `ano build` to have this error.

**Comment by Mausy5043** [comment]
weird:

```
pi@rbian ~/gitino/arduino $ mkdir test
pi@rbian ~/gitino/arduino $ cd test
pi@rbian ~/gitino/arduino/test $ ano init
pi@rbian ~/gitino/arduino/test $ ano build
Searching for Board description file (boards.txt) ... /usr/share/arduino/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /usr/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0.1 (1.0.1)
Searching for Arduino core library ... /usr/share/arduino/hardware/arduino/cores/arduino
Searching for Arduino variants directory ... /usr/share/arduino/hardware/arduino/variants
Searching for Arduino core libraries ... FAILED
Searching for Arduino standard libraries ... /usr/share/arduino/libraries
Searching for Arduino user libraries ... FAILED
Searching for make ... /usr/bin/make
Searching for avr-gcc ... /usr/bin/avr-gcc
Searching for avr-g++ ... /usr/bin/avr-g++
Searching for avr-ar ... /usr/bin/avr-ar
Searching for avr-objcopy ... /usr/bin/avr-objcopy
src/sketch.ino
Searching for Arduino lib version file (version.txt) ... /usr/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0.1 (1.0.1)
Scanning dependencies of src
Scanning dependencies of arduino
src/sketch.cpp
arduino/wiring_digital.c
arduino/wiring_shift.c
arduino/wiring_analog.c
arduino/WInterrupts.c
arduino/wiring_pulse.c
arduino/wiring.c
arduino/Tone.cpp
arduino/Stream.cpp
arduino/WMath.cpp
arduino/CDC.cpp
arduino/main.cpp
arduino/HID.cpp
arduino/HardwareSerial.cpp
arduino/new.cpp
arduino/WString.cpp
arduino/USBCore.cpp
arduino/Print.cpp
arduino/IPAddress.cpp
Linking libarduino.a
Linking firmware.elf
Converting to firmware.hex
pi@rbian ~/gitino/arduino/test $
```

**Comment by scottdarch** [comment]
please sync from arturo's develop branch and `make install` there to install the latest ano version.

Then go into your repository and do `ano clean` then `ano build`

You will see the "FAILED" messages but ano should now continue past them to try to compile without core libraries.

**Comment by Mausy5043** [comment]
On OSX:

```
mausy@argon ~/Documents/git $ mkdir test
mausy@argon ~/Documents/git $ cd test
mausy@argon ~/Documents/git/test $ ano init
mausy@argon ~/Documents/git/test $ ano build
Searching for Board description file (boards.txt) ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /Applications/Arduino.app/Contents/Resources/Java/lib/version.txt
Detecting Arduino software version ...  1.0.5 (1.0.5)
Searching for Arduino core library ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino
Searching for Arduino variants directory ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/variants
Searching for Arduino core libraries ... FAILED
Searching for Arduino standard libraries ... /Applications/Arduino.app/Contents/Resources/Java/libraries
Searching for Arduino user libraries ... /Users/mausy/Documents/Arduino/libraries
Searching for make ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/make
Searching for avr-gcc ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc
Searching for avr-g++ ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++
Searching for avr-ar ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar
Searching for avr-objcopy ... /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy
src/sketch.ino
Searching for Arduino lib version file (version.txt) ... /Applications/Arduino.app/Contents/Resources/Java/lib/version.txt
Detecting Arduino software version ...  1.0.5 (1.0.5)
Scanning dependencies of src
Scanning dependencies of arduino
src/sketch.cpp
arduino/avr-libc/malloc.c
arduino/avr-libc/realloc.c
arduino/WInterrupts.c
arduino/wiring.c
arduino/wiring_analog.c
arduino/wiring_digital.c
arduino/wiring_pulse.c
arduino/wiring_shift.c
arduino/CDC.cpp
arduino/HardwareSerial.cpp
arduino/HID.cpp
arduino/IPAddress.cpp
arduino/main.cpp
arduino/new.cpp
arduino/Print.cpp
arduino/Stream.cpp
arduino/Tone.cpp
arduino/USBCore.cpp
arduino/WMath.cpp
arduino/WString.cpp
Linking libarduino.a
Linking firmware.elf
Converting to firmware.hex
mausy@argon ~/Documents/git/test $
```

**Comment by hachpai** [comment]
For me with the develop branch it gives

```
ano init                                                                                                                                               [0]
Traceback (most recent call last):
  File "/usr/local/bin/ano", line 5, in <module>
    pkg_resources.run_script('arturo==2.0.0', 'ano')
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 507, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources.py", line 1272, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/arturo-2.0.0-py2.7.egg/EGG-INFO/scripts/ano", line 13, in <module>
    main()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arturo-2.0.0-py2.7.egg/arturo/ano.py", line 122, in main
    ArturoCommandLine(Console()).run()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arturo-2.0.0-py2.7.egg/arturo/ano.py", line 113, in run
    args.func()
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arturo-2.0.0-py2.7.egg/arturo/commands/prebuild.py", line 92, in run
    raise MissingRequiredFileException(self.getEnvironment().getSearchPath(), Init.LEGACY_SOURCEFOLDER_NAMES, "Source root folders")
arturo.MissingRequiredFileException: Source root folders
```

**Comment by hachpai** [comment]
Build and clean commands give me 

```
 ano clean                                                                                                                                           [0]
usage: ano [-h] [-v]

Arturo is a command-line toolkit for working with MCU prototype hardware
adhering to the Arduino15 IDE specification for 3rp party hardware:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5---3rd-party-Hardware-
specification TODO: more about gnu make and the core functionality provided by
arturo. --help to get further help. E.g.: ano build --help

optional arguments:
  -h, --help     show this help message and exit
  -v, --verbose  Enable verbose logging
```

**Comment by Mausy5043** [comment]
Odd help text

**Comment by scottdarch** [comment]
Ack, I'm so sorry @hachpai I meant to say "sync from arturo's master branch" not develop. Develop is the WIP 2.0 stuff. Again, really sorry for the foible. Try these instructions instead:

please sync from arturo's master branch and make install there to install the latest ano version.

Then go into your repository and do ano clean then ano build

You will see the "FAILED" messages but ano should now continue past them to try to compile without core libraries.

**Comment by hachpai** [comment]
Sorry I was taken for the w-e. I've re-git cloned the repo, re-make installed, and it still stucks at the same point.
Anyway, why doesn't arturo look inside the .app to find the core?

Nice week everyone!

PH

**Comment by Mausy5043** [comment]
@hachpai : Could you please post a **full** copy of the terminal session?

**Comment by hachpai** [comment]
Here it is :-)

http://pastebin.com/JepnL9Wz

**Comment by scottdarch** [comment]
Sorry for the run around here but your paste shouldn't be possible if you have change db4d0846ee03ff7245f8a83efb3ff81af364f8ff. Can you do a git log in the same directory you are installing ano from and paste the first screen of results?

**Comment by hachpai** [comment]
Yeah, I don't have a lot of time to dedicated to that we're in a rush, sorry :-( 
But it seems weird, i don't know what I do wrong... I've tried to rm ano and reinstall it, always the same.

```
Arturo % git log                                                                                                                                               [1]
commit db4d0846ee03ff7245f8a83efb3ff81af364f8ff
Merge: 05bfcf3 33d8a45
Author: Scott Dixon <scottd.nerd@gmail.com>
Date:   Thu May 14 09:33:06 2015 -0700

    Merge pull request #30 from scottdarch/feature/LibNotFoundFix

    Fix for #29, making libraries optional

commit 33d8a45e2c40148b368400a359f232283287f2eb
Author: Scott Dixon <scottd@fiftythree.com>
Date:   Wed May 13 21:04:38 2015 -0700

    Fix for #29, making libraries optional

    If you don't need 'em you don't need 'em.
    Thanks to @Mausy5043 for diagnosing this issue.

commit 05bfcf3cad0a591dc3edb6995bec07283356bec3
Merge: 4725281 b58a303
Author: Scott Dixon <scottd.nerd@gmail.com>
Date:   Sat May 9 15:48:44 2015 -0700
```

**Comment by Mausy5043** [comment]
I'm baffled.
:open_mouth:

**Comment by hachpai** [comment]
Maybe I'm doing something wrong... but now you've the entire process.

**Comment by Mausy5043** [comment]
What I find intriguing is that you have a directory `/usr/share/arduino`. I don't have that on my Mac.
You might want to try renaming that to something else and see what happens then?

Don't forget to rename it back if it doesn't work. ;-)

**Comment by hachpai** [comment]
It works!
http://pastebin.com/39xhC40X
It was that.
We've it.
Anyway, in ino i've:

```
Searching for Arduino core library ... /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino
```

Should work like that no?

**Comment by Mausy5043** [comment]
Yup. :+1: 
Hope nothing else broke.

**Comment by scottdarch** [comment]
Awesome. Can I close this issue @hachpai ?

**Comment by 23Pstars** [comment]
This issue still exists, I have clone latest version of `ano` (master) on Raspberri Pi then I got this

```
Detecting Arduino software version ...  1.0.5 (2:1.0.5+dfsg2-4)
Searching for Arduino core library ... /usr/share/arduino/hardware/arduino/cores/arduino
Searching for Arduino variants directory ... /usr/share/arduino/hardware/arduino/variants
Searching for Arduino core libraries ... FAILED
Searching for Arduino standard libraries ... /usr/share/arduino/libraries
Searching for Arduino user libraries ... FAILED
```

**Comment by scottdarch** [comment]
Huh. I don't have my PI with me just now. I'll try later tonight (PST).

**Comment by 23Pstars** [comment]
It's just [beep](http://inotool.org/quickstart#building) test project from `ino`

*reply for [#13 ](https://github.com/scottdarch/Arturo/issues/13#issuecomment-181742901)

**Pull request merged**
